name: Docker Build and Push

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build and push Docker image
        working-directory: ./potato_server
        run: |
          docker login --username PiotrFLEURY --password ${{ secrets.GITHUB_TOKEN }} ghcr.io
          docker build -t ghcr.io/piotrfleury/potato:latest .
          docker push ghcr.io/piotrfleury/potato:latest
